//ADD CLIENT ACTION
export const ID_UPDATE = 'ID_UPDATE';

//CLIENT INFORMATION ACTIONS
export const PATIENT_NAME_UPDATE = 'PATIENT_NAME_UPDATE';
export const PATIENT_BIRTHDAY_UPDATE = 'PATIENT_BIRTHDAY_UPDATE';
export const EMAIL_ADDRESS_UPDATE = 'PATIENT_ADDRESS_UPDATE';
export const ADDRESS_UPDATE = 'ADDRESS_UPDATE';
export const PHONE_NUMBER_UPDATE = 'PHONE_NUMBER_UPDATE';

//BEHAVIORAL ACTION PLAN ACTIONS
export const ADD_PROBLEMATIC_BEHVAIOR = 'ADD_PROBLEMATIC_BEHVAIOR';
export const PROBLEMATIC_BEHAVIOR_UPDATE = 'PROBLEMATIC_BEHAVIOR_UPDATE';
export const ADD_FUNCTIONAL_BEHAVIOR = 'ADD_FUNCTIONAL_BEHAVIOR';
export const FUNCTIONAL_GOAL_UPDATE = 'FUNCTIONAL_GOAL_UPDATE';
export const COMMUNICATION_GOAL_UPDATE = 'COMMUNICATION_GOAL_UPDATE';
export const COMMUNICATION_TRIAL_BUTTON = 'COMMUNICATION_TRIAL_BUTTON';
export const ADD_COMMUNICATION_GOAL = 'ADD_COMMUNICATION_GOAL';


//BCBA INFO
export const TOP_OF_PAGE_UPDATE = 'TOP_OF_PAGE_UPDATE';
export const CLIENT_DESCRIPTION_UPDATE = 'CLIENT_DESCRIPTION_UPDATE';
export const BOTTOM_OF_PAGE_UPDATE = 'BOTTOM_OF_PAGE_UPDATE';

//AUTHENTICATION
export const USERNAME_UPDATE = 'USERNAME_UPDATE';
export const PASSWORD_UPDATE = 'PASSWORD_UPDATE';
